package io.runcycles.events.evidence;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.io.InputStream;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.util.Arrays;
import java.util.HexFormat;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Cross-language byte-equality proof for the cycles-evidence-v0.1 recipe.
 *
 * <p>The 13 reference fixtures were generated by the Cycles Python toolchain
 * (RFC 8785 `jcs` + PyNaCl Ed25519) and are independently reproduced by the
 * APS JS verifier. This test makes the Java emitter the third implementation:
 * for every fixture it must (a) recompute the exact {@code evidence_id} and
 * (b) verify the embedded signature against {@code signer_did} — proving the
 * Java JCS + JDK Ed25519 stack agrees with the others byte-for-byte.
 */
class CyclesEvidenceCanonicalizerTest {

    private final ObjectMapper mapper = new ObjectMapper();
    private final CyclesEvidenceCanonicalizer canonicalizer = new CyclesEvidenceCanonicalizer();
    private final EnvelopeSigner signer = new EnvelopeSigner();

    @ParameterizedTest(name = "{0}")
    @ValueSource(strings = {
            "01-decide-allow", "02-reserve-allow", "03-reserve-dry-run-deny",
            "04-reserve-allow-with-caps", "05-commit-success", "06-release-success",
            "07-release-with-reason", "08-reserve-allow-no-trace-id",
            "09-decide-risk-points-allow", "10-reserve-credits-allow",
            "11-reserve-live-budget-exceeded", "12-decide-live-forbidden",
            "13-commit-with-metrics"
    })
    void reproducesEvidenceIdAndVerifiesSignature(String fixture) throws Exception {
        ObjectNode env = loadFixture(fixture);
        String claimedEvidenceId = env.get("evidence_id").asText();
        String signature = env.get("signature").asText();
        String signerDid = env.get("signer_did").asText();

        // (a) recompute the content hash from the canonical bytes
        assertThat(canonicalizer.computeEvidenceId(env))
                .as("evidence_id byte-equality for %s", fixture)
                .isEqualTo(claimedEvidenceId);

        // (b) the embedded signature verifies against signer_did
        byte[] signingBytes = canonicalizer.signingBytes(env, claimedEvidenceId);
        assertThat(signer.verify(signingBytes, signature, signerDid))
                .as("signature verifies for %s", fixture)
                .isTrue();
    }

    @Test
    void signAndVerifyRoundTrip() throws Exception {
        KeyPair kp = KeyPairGenerator.getInstance("Ed25519").generateKeyPair();
        // Raw 32-byte forms are the tails of the DER-encoded keys.
        String privHex = rawTailHex(kp.getPrivate().getEncoded(), 32);
        String pubHex = rawTailHex(kp.getPublic().getEncoded(), 32);

        ObjectNode env = loadFixture("02-reserve-allow");
        env.put("signer_did", pubHex);
        String evidenceId = canonicalizer.computeEvidenceId(env);
        byte[] signingBytes = canonicalizer.signingBytes(env, evidenceId);

        String signature = signer.sign(signingBytes, privHex);
        assertThat(signer.verify(signingBytes, signature, pubHex)).isTrue();
        // a tampered message must not verify
        assertThat(signer.verify("tampered".getBytes(), signature, pubHex)).isFalse();
    }

    @Test
    void verifyFailsClosedOnMalformedInput() {
        byte[] msg = "x".getBytes();
        assertThat(signer.verify(msg, "00".repeat(64), null)).isFalse();      // null key
        assertThat(signer.verify(msg, "00".repeat(64), "abcd")).isFalse();    // short key
        assertThat(signer.verify(msg, null, "00".repeat(32))).isFalse();      // null sig
        assertThat(signer.verify(msg, "00", "00".repeat(32))).isFalse();      // short sig
        assertThat(signer.verify(msg, "zz".repeat(64), "00".repeat(32))).isFalse(); // non-hex sig
    }

    private ObjectNode loadFixture(String name) throws Exception {
        try (InputStream in = getClass().getResourceAsStream(
                "/cycles-evidence-fixtures/" + name + ".json")) {
            return (ObjectNode) mapper.readTree(in);
        }
    }

    private static String rawTailHex(byte[] der, int n) {
        return HexFormat.of().formatHex(Arrays.copyOfRange(der, der.length - n, der.length));
    }
}
